# Generated by Django 2.0.6 on 2019-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.DateField(default='2019-01-01')),
                ('mpg', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
        ),
    ]
